language: java
matrix:
  include:
    - jdk: oraclejdk9

script: >-
    ./gradlew test asciidoctor 
deploy:
  skip_cleanup: true
  provider: script
  script: ./config/travis/deploy_github_pages.sh
  on:
    branch: master

addons:
  apt:
    packages:
      - oracle-java9-installer
after_success:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)